version: "3.9"

services:
  game-service:
    build:
      context: .
      dockerfile: ./deploy/docker/game-service/Dockerfile
    restart: unless-stopped
    networks:
      - rpsls-network
    ports:
      - 8080:8080 # REST
      - 8082:8082 # gRPC
      - 9100:9100 # Metrics prometheus
      - 8000:8000 # Status
      - 40000:40000 # Debug port
    healthcheck:
      test: [ 'CMD', 'curl', '-f', 'http://localhost:8000/live' ]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 20s
    volumes:
      - ./configs/game-service/config.yml:/root/config.yml

  jaeger:
    image: jaegertracing/all-in-one:latest
    restart: unless-stopped
    ports:
      - 6831:6831/udp
      - 16686:16686
    networks:
      - rpsls-network

  prometheus:
    image: prom/prometheus:latest
    restart: unless-stopped
    ports:
      - 9090:9090
    networks:
      - rpsls-network
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  swagger-ui:
    image: swaggerapi/swagger-ui
    ports:
      - 8008:8080
    restart: always
    volumes:
      - ./api/openapi-spec:/docs
    environment:
      SWAGGER_JSON: /docs/api.swagger.json
    depends_on:
      - game-service
    networks:
      - rpsls-network

networks:
  rpsls-network:
    driver: bridge
