name: image

on:
  push:
    tags:
      - '*'

jobs:
  deploy:
    name: Build
    runs-on: ubuntu-latest
    env:
      REGISTRY: ghcr.io
      COMMIT_HASH: ${{ github.sha }}
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set env version
        run: echo "GIT_TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: ${{ runner.os }}-buildx-
      - uses: docker/build-push-action@v2
        with:
          file: ./deploy/docker/game-service/Dockerfile
          push: false
          build-args: |
            VERSION=${{ env.GIT_TAG }}
            COMMIT_HASH=${{ env.COMMIT_HASH }}
          tags: ghcr.io/${{ github.repository_owner }}/rock-paper-scissors-lizard-spock/server:${{ env.GIT_TAG }}
